"""
Scaffold generator -- creates new filer boilerplate from template.

Usage:
    openclerc new-filer --state Oregon --filing-type "Annual Report"
"""
import os
import re

from rich.console import Console

console = Console()


def to_class_name(state: str, filing_type: str) -> str:
    """Convert state + filing type to PascalCase class name."""
    parts = state.split() + filing_type.split()
    return "".join(w.capitalize() for w in parts) + "Filer"


def state_to_code(state: str) -> str:
    """Convert state name to 2-letter code."""
    codes = {
        "alabama": "AL", "alaska": "AK", "arizona": "AZ", "arkansas": "AR",
        "california": "CA", "colorado": "CO", "connecticut": "CT", "delaware": "DE",
        "florida": "FL", "georgia": "GA", "hawaii": "HI", "idaho": "ID",
        "illinois": "IL", "indiana": "IN", "iowa": "IA", "kansas": "KS",
        "kentucky": "KY", "louisiana": "LA", "maine": "ME", "maryland": "MD",
        "massachusetts": "MA", "michigan": "MI", "minnesota": "MN", "mississippi": "MS",
        "missouri": "MO", "montana": "MT", "nebraska": "NE", "nevada": "NV",
        "new hampshire": "NH", "new jersey": "NJ", "new mexico": "NM", "new york": "NY",
        "north carolina": "NC", "north dakota": "ND", "ohio": "OH", "oklahoma": "OK",
        "oregon": "OR", "pennsylvania": "PA", "rhode island": "RI", "south carolina": "SC",
        "south dakota": "SD", "tennessee": "TN", "texas": "TX", "utah": "UT",
        "vermont": "VT", "virginia": "VA", "washington": "WA", "west virginia": "WV",
        "wisconsin": "WI", "wyoming": "WY", "district of columbia": "DC",
    }
    return codes.get(state.lower(), state[:2].upper())


FILER_TEMPLATE = '''"""
{class_name} -- {state_name} {filing_type} filer.

Portal: TODO
Steps: TODO

Generated by: openclerc new-filer
"""
import logging
from typing import Any, Optional

from openclerc.core.base_filer import BaseStateFiler, FilingContext, FilingStep
from openclerc.filers import register_filer
from openclerc.core.utils import split_name, format_address_line, get_signer, detect_form_errors

logger = logging.getLogger("openclerc")


class {class_name}(BaseStateFiler):
    """{state_name} {filing_type} filer."""

    STATE_CODE = "{state_code}"
    STATE_NAME = "{state_name}"
    FILING_CODE = "{filing_code}"
    FILING_NAME = "{filing_type}"
    PORTAL_URL = ""  # TODO: Set portal URL
    TOTAL_STEPS = 1  # TODO: Set total steps

    def get_steps(self) -> list[FilingStep]:
        return [
            FilingStep(1, "Navigate to Portal", "Opening the filing portal",
                       is_page_transition=True,
                       expected_page="Portal landing page"),
            # TODO: Add more steps
        ]

    async def execute_step(
        self,
        step_number: int,
        context: FilingContext,
        browser: Any,
    ) -> FilingStep:
        steps = self.get_steps()
        step = steps[step_number - 1]

        if step_number == 1:
            await browser.navigate(self.PORTAL_URL)
            step.metadata = {{"url": self.PORTAL_URL}}

        # TODO: Add cases for each step

        return step

    def pre_flight_check(self, context: FilingContext) -> list[str]:
        issues = super().pre_flight_check(context)
        # TODO: Add state-specific checks
        return issues


# Register filer
register_filer("{filing_code}", {class_name})
'''

TEST_TEMPLATE = '''"""Tests for {class_name}."""
import pytest
from openclerc.filers.{module_name} import {class_name}
from openclerc.core.base_filer import FilingContext


class Test{class_name}:

    def test_get_steps(self):
        filer = {class_name}()
        steps = filer.get_steps()
        assert len(steps) > 0
        assert steps[0].number == 1

    def test_filing_metadata(self):
        filer = {class_name}()
        meta = filer.get_filing_metadata()
        assert meta["state_code"]
        assert meta["filing_code"]
        assert meta["filing_name"]

    def test_pre_flight_check_missing_name(self):
        filer = {class_name}()
        ctx = FilingContext(entity_name="")
        issues = filer.pre_flight_check(ctx)
        assert any("entity name" in i.lower() for i in issues)

    def test_pre_flight_check_valid(self):
        filer = {class_name}()
        ctx = FilingContext(
            entity_name="Test Corp",
            portal_username="user",
            portal_password="pass",
            principal_address={{"street1": "123 Main St", "city": "Portland", "state": "OR", "zip": "97201"}},
            officers=[{{"full_name": "Jane Doe", "title": "CEO"}}],
        )
        issues = filer.pre_flight_check(ctx)
        # May have state-specific warnings but no fatal errors
        assert not any("entity name" in i.lower() for i in issues)
'''

CONFIG_TEMPLATE = '''{{
  "state": "{state}",
  "filing_type": "{filing_type}",
  "portal_url": "",
  "portal_name": "",
  "login_method": "username_password",
  "captcha": false,
  "draft_save": false,
  "steps_count": 1,
  "notes": "Generated by openclerc new-filer"
}}'''


def create_filer_scaffold(state: str, filing_type: str):
    """Generate a new filer module from template."""
    state_slug = state.lower().replace(" ", "_")
    type_slug = filing_type.lower().replace(" ", "_")
    module_name = f"{state_slug}_{type_slug}"

    filer_path = f"openclerc/filers/{module_name}.py"
    test_path = f"tests/test_{module_name}.py"
    config_path = f"openclerc/filers/{module_name}_config.json"
    screenshots_dir = f"docs/screenshots/{state_slug}/"

    class_name = to_class_name(state, filing_type)
    state_code = state_to_code(state)

    filer_code = FILER_TEMPLATE.format(
        class_name=class_name,
        filing_code=module_name,
        state_code=state_code,
        state_name=state,
        filing_type=filing_type,
    )

    test_code = TEST_TEMPLATE.format(
        module_name=module_name,
        class_name=class_name,
    )

    config_code = CONFIG_TEMPLATE.format(
        state=state,
        filing_type=filing_type,
    )

    # Write files
    os.makedirs(os.path.dirname(filer_path), exist_ok=True)
    os.makedirs(os.path.dirname(test_path), exist_ok=True)
    os.makedirs(screenshots_dir, exist_ok=True)

    with open(filer_path, "w") as f:
        f.write(filer_code)
    with open(test_path, "w") as f:
        f.write(test_code)
    with open(config_path, "w") as f:
        f.write(config_code)

    console.print(f"\n[green]Scaffold created![/green]\n")
    console.print(f"  Filer:  {filer_path}")
    console.print(f"  Tests:  {test_path}")
    console.print(f"  Config: {config_path}")
    console.print(f"\n[yellow]Next steps:[/yellow]")
    console.print(f"  1. Add portal screenshots to {screenshots_dir}")
    console.print(f"  2. Run: openclerc analyze --screenshots {screenshots_dir}")
    console.print(f"  3. Fill in CSS selectors and test with: openclerc run --filer {module_name} --config entity.json")
    console.print(f"  4. Run quality check: openclerc check --filer {module_name}")
    console.print(f"  5. Submit a PR!")
